
# stop requesting MRAM for radio events - improves power consumption if radio FW runs from local RAM
# CONFIG_MPSL_PM_USE_MRAM_LATENCY_SERVICE=n
# CONFIG_MPSL_EXT_CLK_CTRL_NVM_CLOCK_REQUEST=n

CONFIG_PM=y
CONFIG_POWEROFF=y
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_LOG=n
CONFIG_GPIO=n
CONFIG_BOOT_BANNER=n