CONFIG_XIP=n
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="./bootloader/mcuboot/root-rsa-2048.pem"
CONFIG_MCUBOOT_BOOTLOADER_MODE_SINGLE_APP=y
CONFIG_CLOCK_CONTROL=y
CONFIG_NRF_SYS_EVENT=y
CONFIG_ZERO_LATENCY_IRQS=y

CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS="--load-addr 0x23006400"
CONFIG_SRAM_BASE_ADDRESS=0x23006400
#CONFIG_BOOT_DELAY=4000
CONFIG_ARM_MPU=n

# stop requesting MRAM for radio events
CONFIG_MPSL_PM_USE_MRAM_LATENCY_SERVICE=n
CONFIG_MPSL_EXT_CLK_CTRL_NVM_CLOCK_REQUEST=n

CONFIG_PM=y
CONFIG_POWEROFF=y
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_LOG=n
CONFIG_GPIO=n
CONFIG_BOOT_BANNER=n
