#
# Copyright (c) 2025 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_NCS_SAMPLES_DEFAULTS=y

CONFIG_HEAP_MEM_POOL_SIZE=2048

CONFIG_BT=y
CONFIG_BT_CENTRAL=y

CONFIG_BT_SCAN=y
CONFIG_BT_SCAN_FILTER_ENABLE=y
CONFIG_BT_SCAN_NAME_CNT=1
#Arbitrary value but must be larged than CONFIG_PERIPHERAL_ADV_NAME
CONFIG_BT_SCAN_NAME_MAX_LEN=100

CONFIG_BT_USER_PHY_UPDATE=y

# Prevent the host from auto-initiating these procedures as this causes
# unintended and hard-to-debug problems. For example, if a procedure is run at
# the same time as the link is disconnected (in rob_l2cap_001), there will be an
# error in the log.
CONFIG_BT_AUTO_PHY_UPDATE=n
CONFIG_BT_AUTO_DATA_LEN_UPDATE=n
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n
